name: Run unit test
on: push

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Generate project
        run: cmake -S . -B build
      - name: Build project
        run: cmake --build build

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: print directory
        run: ls -la
